[package]
name = "mpl_trifle"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "mpl_trifle"

[dependencies]
borsh = "0.9.3"
shank = "0.0.9"
solana-program = "1.14.1"
spl-token = { version = "3.5.0", features = ["no-entrypoint"] }
thiserror = "1.0.35"
# mpl-token-metadata = { version = "1.4.0", features = ["no-entrypoint"] }
mpl-token-metadata = { path = "../../token-metadata/program" }
num-derive = "0.3.3"
num-traits = "0.2.14"

[dev-dependencies]
solana-sdk = "1.14.1"
solana-program-test = "1.14.1"
