[package]
name = "mpl-trifle"
version = "0.1.0"
description = "Metaplex Composability Program"
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/metaplex-program-library"
license-file = "../../LICENSE"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
borsh = "0.9.3"
shank = "0.0.10"
solana-program = "1.10.40"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "~1.0.5", features = [
    "no-entrypoint",
] }
thiserror = "1.0.35"
mpl-utils = "0.0.5"
mpl-token-metadata = { version = "1.6.2", features = ["no-entrypoint"] }
num-derive = "0.3.3"
num-traits = "0.2.14"
modular-bitfield = "0.11.2"

[dev-dependencies]
solana-sdk = "1.10.40"
solana-program-test = "1.11.5"

[profile.release]
overflow-checks = true     # Enable integer overflow checks.
