[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
auction_house="hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk"
bubblegum="BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "target/deploy/mpl_token_metadata.so"

[[test.genesis]]
address = "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk"
program = "target/deploy/mpl_auction_house.so"

[[test.genesis]]
address = "qntmGodpGkrM42mN68VCZHXnKqDCT8rdY23wFcXCLPd"
program = "target/deploy/mpl_token_entangler.so"

[[test.genesis]]
address = "SaLeTjyUa5wXHnGuewUSyJ5JWZaHwz3TxqUntCE9czo"
program = "target/deploy/mpl_fixed_price_sale.so"

[[test.genesis]]
address = "gdrpGjVffourzkdDRrQmySw4aTHr8a3xmQzzxSwFD1a"
program = "target/deploy/mpl_gumdrop.so"

[[test.genesis]]
address = "WRAPYChf58WFCnyjXKJHtrPgzKXgHp6MD9aVDqJBbGh"
program = "target/deploy/candy_wrapper.so"

[workspace]
members = [
  "token-entangler/program",
  "token-metadata/program",
  "auction-house/program",
  "fixed-price-sale/program",
  "bubblegum/program",
  "candy-wrapper/program"
]

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"

[[test.validator.clone]]
address = "GRoLLzvxpxxu2PGNJMMeZPyMxjAUH9pKqxGXV9DGiceU"

[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.build.json -t 1000000 ./**/js/test/*-test.ts"
