[package]
name = "mpl-token-entangler"
version = "0.1.3"
edition = "2018"
authors = ["Metaplex Developers <dev@metaplex.com>"]
license-file = "../../LICENSE"
description = "MPL Token Entangler"
repository = "https://github.com/metaplex-foundation/metaplex-program-library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "lib"]
name = "mpl_token_entangler"

[features]
no-entrypoint = []
no-idl = []
test-bpf = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
spl-token = { version = "3.5",  features = ["no-entrypoint"] }
spl-associated-token-account = {version = "1.1.1", features = ["no-entrypoint"]}
mpl-token-metadata = { version="1.7.0", features = [ "no-entrypoint" ] }
thiserror = "~1.0"
arrayref = "~0.3.6"

[dev-dependencies]
solana-program-test = "1.14"
solana-sdk = "1.14"

[profile.release]
overflow-checks = true     # Enable integer overflow checks.
