[package]
name = "mpl_gumdrop"
version = "0.0.1"
description = "A Solana program for distributing tokens and NFTs according to a Merkle root."
authors = [ "Lawrence Wu <larry.wu@solana.com>" ]
keywords = ["solana"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "mpl_gumdrop"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.19.0"
anchor-spl = "0.19.0"
solana-program = "1.9.5"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "~1.0.3", features = [ "no-entrypoint" ] }
metaplex-token-metadata = { git = "https://github.com/lwus/metaplex/", rev = "81f77c5c", features = [ "no-entrypoint" ] }
nft-candy-machine = { git = "https://github.com/lwus/metaplex/", rev = "81f77c5c", features = [ "cpi" ] }
