[workspace]
members=[
  "macro",
  "program"
]

[profile.release]
overflow-checks = true     # Enable integer overflow checks.
strip = true  # Automatically strip symbols from the binary.
opt-level = "z" 
lto = true
codegen-units = 1
