[package]
name = "mpl-candy-machine-state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9.2"
solana-program = "1.9.18"

