[package]
name = "mpl-utils"
version = "0.3.3"
edition = "2021"
description = "MPL Core Utils library"
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/metaplex-program-library"
license-file = "../../../LICENSE"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]
path = "src/lib.rs"

[dependencies]
arrayref = "0.3.6"
solana-program = ">= 1.14.13, < 1.17"
spl-token-2022 = { version = ">= 0.6.0, < 0.9", features = ["no-entrypoint"], optional = true }

[features]
spl-token = ["spl-token-2022"]
default = ["spl-token"]

[profile.release]
overflow-checks = true     # Enable integer overflow checks.
