name: Label Automations

on:
  issues:
    types: [labeled, unlabeled]
  discussion:
    types: [labeled, unlabeled]
  # pull_request:
    # types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write
  discussions: write
  # pull-requests: write

jobs:
  issue-label-automations:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2
        with:
          config-path: '.github/configs/issue-label-automations.yml'
          process-only: 'issues, discussions'
